// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `WrappedTokenRefresher`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `refresh`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `from_func`

class DartTokenInfo {
  final String token;

  /// unixtime (in seconds) of expiration
  final BigInt expiration;

  const DartTokenInfo({required this.token, required this.expiration});

  @override
  int get hashCode => token.hashCode ^ expiration.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DartTokenInfo &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          expiration == other.expiration;
}
