// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'token_refresh.freezed.dart';
part 'token_refresh.g.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `WrappedTokenRefresher`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `refresh`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `from_func`

@freezed
sealed class DartTokenInfo with _$DartTokenInfo {
  const factory DartTokenInfo({
    required String token,
    required BigInt expiration,
  }) = _DartTokenInfo;

  factory DartTokenInfo.fromJson(Map<String, dynamic> json) =>
      _$DartTokenInfoFromJson(json);
}
