on:
  push:
    branches:
    - main

name: Precompile Binaries

jobs:
  Precompile:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macOS-latest
          - windows-latest
          - windows-11-arm
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: Install GTK
        if: (matrix.os == 'ubuntu-latest') || (matrix.os == 'ubuntu-24.04-arm')
        run: sudo apt-get update && sudo apt-get install libgtk-3-dev
      - name: Precompile
        if: (matrix.os == 'ubuntu-24.04-arm') || (matrix.os == 'macOS-latest') || (matrix.os == 'windows-latest') || (matrix.os == 'windows-11-arm')
        run: dart run build_tool precompile-binaries -v --manifest-dir=../../rust --repository=NathanKolbas/xet-core-dart
        working-directory: cargokit/build_tool
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          PRIVATE_KEY: ${{ secrets.RELEASE_PRIVATE_KEY }}
      - name: Precompile (with Android)
        if: (matrix.os == 'ubuntu-latest')
        run: dart run build_tool precompile-binaries -v --manifest-dir=../../rust --repository=NathanKolbas/xet-core-dart --android-sdk-location=/usr/local/lib/android/sdk --android-ndk-version=27.0.12077973 --android-min-sdk-version=19
        working-directory: cargokit/build_tool
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          PRIVATE_KEY: ${{ secrets.RELEASE_PRIVATE_KEY }}
